import tkinter
from tkinter import *

win = Tk()
win.geometry('500x400')
win.configure(bg='lightgreen')
b = Label(win,text='Student From',bg='lightgreen')
b.place(x=200,y=00)

l1 = Label(win, text='First Name',bg='lightgreen')
l1.place(x=10,y=10)
l2 = Label(win, text='Last Name',bg='lightgreen')
l2.place(x=10,y=40)
l3 = Label(win, text = 'Email',bg='lightgreen')
l3.place(x=10,y=70)
l4 = Label(win,text= 'Address',bg='lightgreen')
l4.place(x=10,y=100)
l5 = Label(win,text='Gender',bg='lightgreen')
l5.place(x=10,y=130)
l6 = Label(win,text='Class',bg='lightgreen')
l6.place(x=10,y=220)
l7 = Label(win,text='Grade',bg='lightgreen')
l7.place(x=10,y=250)
l8 = Label(win,text='Course',bg='lightgreen')
l8.place(x=10,y=280)
l9 = Label(win,text='About Your Self',bg='lightgreen')
l9.place(x=10,y=310)

x1 = StringVar()
x2 = StringVar()
x3 = StringVar()
x4 = StringVar()
x6 = StringVar()
x7 = StringVar()
x8 = StringVar()
x9 = StringVar()

e1 = Entry(win,textvariable=x1)
e1.place(x=75,y=10)
e2 = Entry(win,textvariable=x2)
e2.place(x=75,y=40)
e3 = Entry(win,textvariable=x3)
e3.place(x=75,y=70)
e4 =  Entry(win, textvariable=x4,)
e4.place(x=75,y=100)
var = IntVar
r1 = Radiobutton(win, text='Male', variable='var', value=1, height=2, width=4,bg='lightgreen')
r1.place(x=75,y=120)
r1 = Radiobutton(win, text='Female', variable='var', value=2, height=2, width=5,bg='lightgreen')
r1.place(x=75,y=150)
r1 = Radiobutton(win, text='Other', variable='var', value=3, height=2, width=4,bg='lightgreen')
r1.place(x=75,y=180)
e6 = Entry(win,textvariable=x6)
e6.place(x=75,y=220)
e7 = Entry(win,textvariable=x7)
e7.place(x=75,y=250)
e8 = Entry(win,textvariable=x8)
e8.place(x=75,y=280)
e9 = Entry(win,textvariable=x9)
e9.place(x=110,y=310)
b = Button(win,text="Submit" , activebackground='blue')
b.place(x=220,y=350)


win.mainloop()
